-- Table作成
-- アカウント
CREATE TABLE ACCOUNT (
  USER_ID varchar2(16),
  PASSWORD varchar2(16),
  DELETE_FLAG varchar2(1),
  PASSWORD_EXPIRE date,
  REMARKS varchar2(256),
  FILE_ENCLOSURE_CHAR_FLAG varchar2(1),
  UPDATE_DATE date,
  REG_DATE date;
);

-- 健康情報
CREATE TABLE HEALTH_INFO (
  DATA_ID varchar2(16),
  USER_ID varchar2(16),
  HEIGHT number(8),
  WEIGHT number(8),
  BMI number(8),
  STANDARD_WEIGHT number(8),
  USER_STATUS varchar2(1),
  REG_DATE date;
);

-- メール情報
CREATE TABLE MAIL_INFO (
  USER_ID varchar2(16),
  MAIL_ADDRESS varchar2(256),
  MAIL_PASSWORD varchar2(16),
  UPDATE_DATE date,
  REG_DATE date;
);

-- コード
CREATE TABLE CODE (
  MAIN_KEY varchar2(256),
  SUB_KEY varchar2(256),
  VALUE varchar2(256);
);

-- 初期データ投入
-- アカウント
INSERT INTO ACCOUNT VALUES ('admin','admin','0','9999/12/31','adminのアカウントです','0','9999/12/31','9999/12/31');

-- コード
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','DOWN','10');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','EVEN','20');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','INCREASE','30');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','DOWN_MESSAGE','減りました');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','EVEN_MESSAGE','変化ありません');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','INCREASE_MESSAGE','増えました');
INSERT INTO CODE VALUES ('PAGE_VIEW','INPUT','0');
INSERT INTO CODE VALUES ('PAGE_VIEW','CONFIRM','1');
INSERT INTO CODE VALUES ('PAGE_VIEW','COMPLETE','2');
INSERT INTO CODE VALUES ('FLAG','TRUE','1');
INSERT INTO CODE VALUES ('FLAG','FALSE','0');
INSERT INTO CODE VALUES ('CSV_FILE_NAME','HEALTH_INFO','HealthInfo.csv');
INSERT INTO CODE VALUES ('CSV_FILE_NAME','REFERNCE_RESULT','ReferenceResult.csv');


