INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','DOWN','10');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','EVEN','20');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','INCREASE','30');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','DOWN_MESSAGE','å∏ÇËÇ‹ÇµÇΩ');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','EVEN_MESSAGE','ïœâªÇ†ÇËÇ‹ÇπÇÒ');
INSERT INTO CODE VALUES ('HEALTH_INFO_USER_STATUS','INCREASE_MESSAGE','ëùÇ¶Ç‹ÇµÇΩ');
INSERT INTO CODE VALUES ('PAGE_VIEW','INPUT','0');
INSERT INTO CODE VALUES ('PAGE_VIEW','CONFIRM','1');
INSERT INTO CODE VALUES ('PAGE_VIEW','COMPLETE','2');
INSERT INTO CODE VALUES ('FLAG','TRUE','1');
INSERT INTO CODE VALUES ('FLAG','FALSE','0');
INSERT INTO CODE VALUES ('CSV_FILE_NAME','HEALTH_INFO','HealthInfo.csv');
INSERT INTO CODE VALUES ('CSV_FILE_NAME','REFERNCE_RESULT','ReferenceResult.csv');

